// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjPMW520a8mO1kMZi6zS30Prm4cZ_NGG8',
    appId: '1:488053861316:web:2ad297c8b74ac7c55b1291',
    messagingSenderId: '488053861316',
    projectId: 'proj-exte-alexandre',
    authDomain: 'proj-exte-alexandre.firebaseapp.com',
    storageBucket: 'proj-exte-alexandre.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjAwVOTJzjXf_vlOHPmk-cQciVnYgQcrM',
    appId: '1:488053861316:android:15f642c9caa51f2a5b1291',
    messagingSenderId: '488053861316',
    projectId: 'proj-exte-alexandre',
    storageBucket: 'proj-exte-alexandre.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdZjkVUMrYXnEziRwRiFmcA2yOmv57iU',
    appId: '1:488053861316:ios:f360ade8c0a681535b1291',
    messagingSenderId: '488053861316',
    projectId: 'proj-exte-alexandre',
    storageBucket: 'proj-exte-alexandre.firebasestorage.app',
    iosBundleId: 'com.example.projetoExtensionistaAlexandreBarreto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjdZjkVUMrYXnEziRwRiFmcA2yOmv57iU',
    appId: '1:488053861316:ios:f360ade8c0a681535b1291',
    messagingSenderId: '488053861316',
    projectId: 'proj-exte-alexandre',
    storageBucket: 'proj-exte-alexandre.firebasestorage.app',
    iosBundleId: 'com.example.projetoExtensionistaAlexandreBarreto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjPMW520a8mO1kMZi6zS30Prm4cZ_NGG8',
    appId: '1:488053861316:web:38467722e08c23665b1291',
    messagingSenderId: '488053861316',
    projectId: 'proj-exte-alexandre',
    authDomain: 'proj-exte-alexandre.firebaseapp.com',
    storageBucket: 'proj-exte-alexandre.firebasestorage.app',
  );

}